### ISSUE TITLE
TrueClass, FalseClass, NilClass, Symbol and Numeric are duplicable

### ISSUE THREAD

**Issue by dfaulken** [umts/custom-cops#4]
From the Rails changelog:

![screen shot 2016-12-22 at 9 42 16 am](https://cloud.githubusercontent.com/assets/3988134/21429854/9d8148f0-c82e-11e6-8d36-8d53bd244b99.png)

We should release a version deprecating this cop as of Ruby 2.4.

**Comment by werebus** [comment]
Huh.  I can't see evidence of this yet

```ruby
RUBY_DESCRIPTION  #=> "ruby 2.4.0preview3 (2016-11-07 trunk 56661) [x86_64-linux]"

[true, false, nil, :a_symbol, 1].map do |o|
  o.dup rescue $!
end  #=> [#<TypeError: can't dup TrueClass>, #<TypeError: can't dup FalseClass>, #<TypeError: can't dup NilClass>, #<TypeError: can't dup Symbol>, #<TypeError: can't dup Integer>]

**Comment by dfaulken** [comment]
https://bugs.ruby-lang.org/issues/12979

**Comment by dfaulken** [comment]
So then, my reading is that this doesn't affect the cop at all? Feel free to close if you concur.
